In [1]:
import pandas as pd
import numpy as np
import seaborn as sms
import matplotlib.pyplot as plt

In [2]:
ls

 Volume in drive C is Windows
 Volume Serial Number is AC60-AD3D

 Directory of C:\Users\Lakshmi Priya\OneDrive\Documents\GitHub\Organic-food-tracebality

07-08-2026  23:33    <DIR>          .
27-07-2026  22:30    <DIR>          ..
07-08-2026  22:43    <DIR>          .ipynb_checkpoints
27-07-2026  23:29                 5 .python-version
28-07-2026  22:37    <DIR>          .venv
06-08-2026  22:39    <DIR>          __pycache__
06-08-2026  22:36             7,335 app.py
06-08-2026  20:48    <DIR>          assets
03-08-2026  21:45            13,176 cart_page.py
07-08-2026  23:33               137 categories.csv
06-08-2026  22:41            12,294 categories.ipynb
02-08-2026  21:43             2,964 categories.py
06-08-2026  22:36             2,526 category_page.py
06-08-2026  22:36    <DIR>          components
06-08-2026  22:36             1,059 config.py
06-08-2026  22:36            26,339 db_manager.py
06-08-2026  22:36             2,597 favourites.py
01-08-2026  23:05             1,461 init_db.py
06-08-2026  22:36            11,297 login_page.py
27-07-2026  23:29               102 main.py
31-07-2026  21:16            24,576 organic_food.db
29-07-2026  23:07    <DIR>          pages
31-07-2026  23:01    <DIR>          product_icons
07-08-2026  23:31            42,603 products.csv
07-08-2026  23:33            26,461 Products.ipynb
06-08-2026  22:36            20,659 products.py
28-07-2026  22:36               237 pyproject.toml
27-07-2026  22:30                54 README.md
31-07-2026  22:14                59 requirements.txt
27-07-2026  23:36                23 sample.txt
06-08-2026  22:36             4,702 schema.sql
03-08-2026  21:46             5,947 traceability_page.py
30-07-2026  22:45    <DIR>          utils
28-07-2026  22:36           115,081 uv.lock
03-08-2026  21:45             2,772 wishlist_page.py
              25 File(s)        324,466 bytes
              10 Dir(s)  127,681,933,312 bytes free

In [3]:
categories = pd.read_csv("categories.csv")

In [4]:
categories

    CategoryID CategoryName
0            1  Confections
1            2   Shell fish
2            3      Cereals
3            4        Dairy
4            5    Beverages
5            6      Seafood
6            7         Meat
7            8        Grain
8            9      Poultry
9           10       Snails
10          11      Produce

Fruits
Vegetables
Grains
Pulses
Dairy
Spices
Beverages
Dry Fruits
Herbs
Oils

In [5]:

categories.loc[categories['CategoryID'] == 1, 'CategoryName'] = 'Fruits'
categories.loc[categories['CategoryID'] == 2, 'CategoryName'] = 'Vegetables'
categories.loc[categories['CategoryID'] == 3, 'CategoryName'] = 'Grains'
categories.loc[categories['CategoryID'] == 4, 'CategoryName'] = 'Pulses'
categories.loc[categories['CategoryID'] == 5, 'CategoryName'] = 'Dairy'
categories.loc[categories['CategoryID'] == 6, 'CategoryName'] = 'Spices'
categories.loc[categories['CategoryID'] == 7, 'CategoryName'] = 'Beverages'
categories.loc[categories['CategoryID'] == 8, 'CategoryName'] = 'Dry Fruits'
categories.loc[categories['CategoryID'] == 9, 'CategoryName'] = 'Millets'
categories.loc[categories['CategoryID'] == 10,'CategoryName'] = 'Oils'

In [6]:
categories.head(10)

   CategoryID CategoryName
0           1       Fruits
1           2   Vegetables
2           3       Grains
3           4       Pulses
4           5        Dairy
5           6       Spices
6           7    Beverages
7           8   Dry Fruits
8           9      Millets
9          10         Oils

In [7]:
categories=categories.head(10)

In [8]:
categories.shape

(10, 2)

In [9]:
categories.to_csv("categories.csv",header=True)