In [1]:
import pandas as pd
import numpy as np
import seaborn as sms
import matplotlib.pyplot as plt

In [3]:
ls

 Volume in drive C is Windows
 Volume Serial Number is AC60-AD3D

 Directory of C:\Users\Lakshmi Priya\OneDrive\Documents\GitHub\Organic-food-tracebality

11-08-2026  23:01    <DIR>          .
27-07-2026  22:30    <DIR>          ..
11-08-2026  22:56    <DIR>          .ipynb_checkpoints
27-07-2026  23:29                 5 .python-version
28-07-2026  22:37    <DIR>          .venv
06-08-2026  22:39    <DIR>          __pycache__
06-08-2026  22:36             7,335 app.py
06-08-2026  20:48    <DIR>          assets
03-08-2026  21:45            13,176 cart_page.py
07-08-2026  23:33               156 categories.csv
07-08-2026  23:35            11,893 categories.ipynb
02-08-2026  21:43             2,964 categories.py
06-08-2026  22:36             2,526 category_page.py
06-08-2026  22:36    <DIR>          components
06-08-2026  22:36             1,059 config.py
11-08-2026  22:53         9,774,936 Customer.csv
11-08-2026  22:54            14,137 Customer.ipynb
07-08-2026  23:41         4,436,738 customers.csv
06-08-2026  22:36            26,339 db_manager.py
06-08-2026  22:36             2,597 favourites.py
01-08-2026  23:05             1,461 init_db.py
06-08-2026  22:36            11,297 login_page.py
27-07-2026  23:29               102 main.py
31-07-2026  21:16            24,576 organic_food.db
29-07-2026  23:07    <DIR>          pages
31-07-2026  23:01    <DIR>          product_icons
07-08-2026  23:31            42,603 products.csv
07-08-2026  23:33            26,461 Products.ipynb
06-08-2026  22:36            20,659 products.py
28-07-2026  22:36               237 pyproject.toml
27-07-2026  22:30                54 README.md
31-07-2026  22:14                59 requirements.txt
11-08-2026  23:01       145,752,064 sales.csv
11-08-2026  23:01             3,817 Sales.ipynb
27-07-2026  23:36                23 sample.txt
06-08-2026  22:36             4,702 schema.sql
03-08-2026  21:46             5,947 traceability_page.py
30-07-2026  22:45    <DIR>          utils
28-07-2026  22:36           115,081 uv.lock
03-08-2026  21:45             2,772 wishlist_page.py
              30 File(s)    160,305,776 bytes
              10 Dir(s)  124,653,838,336 bytes free

In [4]:
s= pd.read_csv("Sales.csv")

In [5]:
s.head()

,SalesID,SalesPersonID,CustomerID,ProductID,Quantity,Discount,TotalPrice,SalesDate,TransactionNumber
0,1,6,27039,381,7,0.0,0.0,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G
1,2,16,25011,61,7,0.0,0.0,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8
2,3,13,94024,23,24,0.0,0.0,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0
3,4,8,73966,176,19,0.2,0.0,2018-04-07 14:43:55.420,R3DR9MLD5NR76VO17ULE
4,5,10,32653,310,9,0.0,0.0,2018-02-12 15:37:03.940,4BGS0Z5OMAZ8NDAFHHP3

CREATE TABLE `Order_Details` (
	`order_id` INT NOT NULL AUTO_INCREMENT,
	`customer_id` INT NOT NULL,
	`product_id` INT NOT NULL,
	`product_count` INT NOT NULL,
	`product_price` DECIMAL(10,2) NOT NULL,
	`product_discount` DECIMAL(5,2) NOT NULL,
	`price_after_discount` DECIMAL(10,2) NOT NULL,
	`order_date` DATE NOT NULL,
	`order_time` TIME NOT NULL,
	PRIMARY KEY (`order_id`) USING BTREE,
	INDEX `fk_order_customer` (`customer_id`) USING BTREE,
	INDEX `fk_order_product` (`product_id`) USING BTREE,
	CONSTRAINT `fk_order_customer` FOREIGN KEY (`customer_id`) REFERENCES `Customer_Details` (`customer_id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `fk_order_product` FOREIGN KEY (`product_id`) REFERENCES `Product` (`product_id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=307
;

In [11]:
p=pd.read_csv("Products.csv")

In [12]:
p.head()

,product_id,category_id,product_name,price,manufacture_date,expiry_date,quantity,discount
0,1,3,Flour - Whole Wheat,74.2988,2018-02-16 08:21:49.190,2018-03-18 08:21:49.190,73,10
1,2,3,Cookie Chocolate Chip With,91.2329,2017-02-12 11:39:10.970,2017-03-14 11:39:10.970,100,29
2,3,9,Onions - Cippolini,9.1379,2018-03-15 08:11:51.560,2018-04-14 08:11:51.560,78,17
3,4,9,"Sauce - Gravy, Au Jus, Mix",54.3055,2017-07-16 00:46:28.880,2017-08-15 00:46:28.880,95,24
4,5,2,Artichokes - Jerusalem,65.4771,2017-08-16 14:13:35.430,2017-09-15 14:13:35.430,98,17

In [15]:
s.rename(columns={'ProductID': 'product_id'}, inplace=True)

In [15]:
df=pd.merge(s,p,on="product_id")

In [16]:
df.head()

,SalesID,SalesPersonID,CustomerID,product_id,Quantity,Discount,TotalPrice,SalesDate,TransactionNumber,category_id,product_name,price,manufacture_date,expiry_date,quantity,discount
0,1,6,27039,381,7,0.0,0.0,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G,1,Vaccum Bag 10x13,44.2337,2018-01-06 22:26:53.580,2018-02-05 22:26:53.580,55,15
1,2,16,25011,61,7,0.0,0.0,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8,8,Sardines,62.5460,2017-12-03 21:41:12.420,2018-01-02 21:41:12.420,61,8
2,3,13,94024,23,24,0.0,0.0,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0,11,Crab - Imitation Flakes,79.0184,2017-08-19 07:18:29.890,2017-09-18 07:18:29.890,34,27
3,4,8,73966,176,19,0.2,0.0,2018-04-07 14:43:55.420,R3DR9MLD5NR76VO17ULE,6,Smirnoff Green Apple Twist,81.3167,2017-08-27 17:08:59.840,2017-09-26 17:08:59.840,66,5
4,5,10,32653,310,9,0.0,0.0,2018-02-12 15:37:03.940,4BGS0Z5OMAZ8NDAFHHP3,9,Coffee - Dark Roast,79.9780,2018-01-14 19:33:15.530,2018-02-13 19:33:15.530,64,15

In [19]:
df.drop(['SalesPersonID','manufacture_date','expiry_date','quantity','Discount','TotalPrice','product_name'],inplace=True,axis=1)

In [20]:
df.head()

,SalesID,CustomerID,product_id,Quantity,SalesDate,TransactionNumber,category_id,price,discount
0,1,27039,381,7,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G,1,44.2337,15
1,2,25011,61,7,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8,8,62.5460,8
2,3,94024,23,24,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0,11,79.0184,27
3,4,73966,176,19,2018-04-07 14:43:55.420,R3DR9MLD5NR76VO17ULE,6,81.3167,5
4,5,32653,310,9,2018-02-12 15:37:03.940,4BGS0Z5OMAZ8NDAFHHP3,9,79.9780,15

In [ ]:
CREATE TABLE `Order_Details` (
	`order_id` INT NOT NULL AUTO_INCREMENT,
	`customer_id` INT NOT NULL,
	`product_id` INT NOT NULL,
	`product_count` INT NOT NULL,
	`product_price` DECIMAL(10,2) NOT NULL,
	`product_discount` DECIMAL(5,2) NOT NULL,
	`price_after_discount` DECIMAL(10,2) NOT NULL,
	`order_date` DATE NOT NULL,
	`order_time` TIME NOT NULL,
	PRIMARY KEY (`order_id`) USING BTREE,
	INDEX `fk_order_customer` (`customer_id`) USING BTREE,
	INDEX `fk_order_product` (`product_id`) USING BTREE,
	CONSTRAINT `fk_order_customer` FOREIGN KEY (`customer_id`) REFERENCES `Customer_Details` (`customer_id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `fk_order_product` FOREIGN KEY (`product_id`) REFERENCES `Product` (`product_id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=307
;